########################################################

### undertow setting.

########################################################
server:
  port: 9084
  undertow:
    accesslog:
      #Undertow access log directory.
      dir: /
      #Whether to enable the access log.
      enabled: false
      #Format pattern for access logs.(%t [%I] %a %r %s (%b Byte) (%T ms) )
      pattern: common
      #Log file name prefix.
      prefix: access_log.
      #Whether to enable access log rotation.
      rotate: true
      #Log file name suffix.
      suffix: log
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    #每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024 
    # Allocate buffers outside the Java heap. The default is derived from the maximum amount of memory that is available to the JVM. 
    direct-buffers: true
    # Whether servlet filters should be initialized on startup.
    eager-filter-init: true
    # Number of I/O threads to create for the worker. The default is derived from the number of available processors.
    io-threads: 2
    # Maximum size in bytes of the HTTP post content. When the value is -1, the default, the size is unlimited.
    max-http-post-size: -1
    # Number of worker threads. The default is 8 times the number of I/O threads.默认值是IO线程数*8
    worker-threads: 16 
########################################################

### database setting.

########################################################
spring:
  datasource:
    # JDBC 配置(驱动类自动从url的mysql识别,数据源类型自动识别)
    url: jdbc:mysql://127.0.0.1:3306/central-transaction?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false 
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
########################################################

### mybatis setting.

########################################################    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
########################################################

### log4j setting.

########################################################
logging:
  config: classpath:log4j2-dev.xml
########################################################

### 服务监控

########################################################
# 开启所有端点2.0以后默认关闭的
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
########################################################

### redis setting.

########################################################
#单机配置
---
spring:
  redis:
    password: '123456'
    database: 0  #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    timeout: 10000  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    #单机配置
    host: 127.0.0.1
    port: 6379
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    lettuce:
      pool:
        # 连接池最大活跃连接数（使用负值表示没有限制） 默认 8,负数为不限制
        max-active: 20
        # 连接池中的最大空闲连接 默认 8
        max-idle: 20
        # 最小空闲连接数
        min-idle: 15
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 8000
      shutdown-timeout: 8000ms
########################################################

### tx-lcn logger setting.

########################################################
tx-lcn:
  logger:
    enabled: true
########################################################

### TxManager setting.

########################################################
---
tx-lcn:
  manager:
    #TM监听IP. 默认为 127.0.0.1
    host: 127.0.0.1 
    #TM监听Socket端口. 默认为 ${server.port} - 100
    port: 9005
    # 心跳检测时间(ms). 默认为 300000
    heart-time: 15000 #心跳检测时间(ms)
    # 分布式事务执行总时间(ms). 默认为36000
    dtx-time: 30000 
    # 事务处理并发等级. 默认为机器逻辑核心数5倍
    concurrent-level: 10
    # TM后台登陆密码，默认值为codingapi
    admin-key: 123456
    # 分布式事务锁超时时间 默认为-1，当-1时会用tx-lcn.manager.dtx-time的时间
    dtx-lock-time: 20000
    # 雪花算法的sequence位长度，默认为12位.
    seq-len: 12
    # 异常回调开关。开启时请制定ex-url
    ex-url-enabled: false
    # 事务异常通知（任何http协议地址。未指定协议时，为TM提供内置功能接口）。默认是邮件通知
    ex-url: /provider/email-to/***@**.com
  #参数延迟删除时间单位ms
  message:
    netty: 
      # 参数延迟删除时间单位ms  默认为dtx-time值
      attr-delay-time: 20000