########################################################

### undertow setting.

########################################################
server:
  undertow:
    accesslog:
      #Undertow access log directory.
      dir: /
      #Whether to enable the access log.
      enabled: false
      #Format pattern for access logs.(%t [%I] %a %r %s (%b Byte) (%T ms) )
      pattern: common
      #Log file name prefix.
      prefix: access_log.
      #Whether to enable access log rotation.
      rotate: true
      #Log file name suffix.
      suffix: log
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    #每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024 
    # Allocate buffers outside the Java heap. The default is derived from the maximum amount of memory that is available to the JVM. 
    direct-buffers: true
    # Whether servlet filters should be initialized on startup.
    eager-filter-init: true
    # Number of I/O threads to create for the worker. The default is derived from the number of available processors.
    io-threads: 2
    # Maximum size in bytes of the HTTP post content. When the value is -1, the default, the size is unlimited.
    max-http-post-size: -1
    # Number of worker threads. The default is 8 times the number of I/O threads.默认值是IO线程数*8
    worker-threads: 16 

########################################################

### i18n setting.

########################################################
---
spring:
  messages:
    basename: i18n/messages   #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    cache-duration: 3600  #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    encoding: UTF-8   #设定Message bundles的编码，默认: UTF-8
########################################################

### log4j setting.

########################################################
logging:
  config: classpath:log4j2-dev.xml
########################################################

### 服务监控

########################################################
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'   #开启所有端点2.0以后默认关闭的
########################################################

### redis setting. 2.0以后redis的连接池改为了lettuce，lettuce能够支持redis4，需要java8及以上

########################################################
#单机配置
---
spring:
  redis:
    database: 1  #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    timeout: 5000ms  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    #单机配置
    host: 127.0.0.1
    port: 6379
#    password: # 密码（默认为空）
    ssl: false
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    lettuce:
      pool:
        # 连接池最大活跃连接数（使用负值表示没有限制） 默认 8,负数为不限制
        max-active: 2
        # 连接池中的最大空闲连接 默认 8
        max-idle: 2
        # 最小空闲连接数
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 35000ms
      shutdown-timeout: 35000ms
########################################################

### database setting.

########################################################
---
spring:
  datasource:
    #数据源single,multi
    isSingle: true
    # JDBC 配置(驱动类自动从url的mysql识别,数据源类型自动识别)
    url: jdbc:mysql://10.67.31.148:3306/yum_report_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: yum
    password: yum123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 2
      max-active: 12
      #获取连接等待超时时间
      max-wait: 30000
      validation-query: select 1
      validation-query-timeout: 5
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      remove-abandoned: true
      remove-abandoned-timeout: 120
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 30000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 60000
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #监控统计拦截的filters
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  pagehelper:
    # 分页注册别名默认mysql（hsqldb、h2、postgresql、phoenix、mysql、mariadb、sqlite、oracle、db2、informix、sqlserver、sqlserver2012、derby、dm-达梦）
    helperDialect: mysql
########################################################

### delay setting.

########################################################
---
spring:
  delay:
    name : dq_demo